version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
      
    ports:
      - '5432:5432'
  app:
    build:
      context: .
    expose:
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: always
    environment:
      HOST: ${HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      API_VERSION: ${API_VERSION}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      EXPIRES_IN: ${EXPIRES_IN}
      SESSION_KEY: ${SESSION_KEY}
      DEV_DATABASE_URL: ${DEV_DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      CLIENTID: ${CLIENTID}
      CLIENTSECRET: ${CLIENTSECRET}

    command: npm start
