version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      - db
    # env_file:
    #   - .env
    environment:
      HOST: ${HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      API_VERSION: ${API_VERSION}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      EXPIRES_IN: ${EXPIRES_IN}
      SESSION_KEY: ${SESSION_KEY}
      CLIENTID: ${CLIENTID}
      CLIENTSECRET: ${CLIENTSECRET}
      DATABASE_URL: postgres://postgres:password@db/mydb
      DEV_DATABASE_URL: postgres://postgres:password@db/mydb
      TEST_DATABASE_URL: postgres://postgres:password@db/mydb
    command: npm start
volumes:
  db-data:
