version: 2.1
orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/base:stable
      - image: cimg/node:19.6.0
    working_directory: ~/app
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn install
      - run: yarn build
      - store_artifacts:
          path: dist
          destination: dist
  test:
    docker:
      - image: cimg/base:stable
      - image: cimg/node:19.6.0
      # - image: circleci/postgres
      # - image: cimg/postgres:15.1-postgis
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_DB: circle_test
      #     POSTGRES_PASSWORD: mypassword
      #     POSTGRES_HOST_AUTH_METHOD: trust
          
    steps:
      - checkout
      - node/install:
          install-yarn: true
      # - run: |
      #     wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
      #     chmod +x wait-for-it.sh
      #     ./wait-for-it.sh -t 60 localhost:5432 -- echo "PostgreSQL is up and running"
      # - run: sudo service postgresql start
      # - run: psql -c 'create database circle_test;' -U postgres
      - run: yarn install
      - run: yarn upgrade
      - run: yarn test
      - run: yarn add coveralls
      - run: yarn test:coverage
      # - run:
      #     name: Install Node.js and npm
      #     command: sudo apt-get update
      - run: 
          command: sudo apt-get install -y nodejs
      - run: 
          command: sudo apt-get update && sudo apt-get install yarn
      - run:
          name: Install Node.js and npm
          command: sudo apt-get install -y npm
      - store_artifacts:
          path: coverage
          destination: coverage
      - run:
          command: sudo npm update
      - run: 
          command: sudo npm install coveralls
      - coveralls/upload
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build