name: Test

on:
  push:
    branches: 
      - develop
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [develop,main]
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      # - name: Start PostgreSQL container
      #   uses: docker/compose@v2
      #   with:
      #     compose-file: docker-compose.yml
      #     project-name: postgres
      #     service-ports: 5432:5432
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d

      - name: Wait for 1 minutes
        run: sleep 60

      - name: Install dependencies
        run: npm install
      - name: Run tests and generate coverage report
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/mydatabase
          TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/mydatabase
          CI: true
          NODE_ENV: test
        run: npm run test:coverage
          
      - name: Upload coverage report to Coveralls
        # uses: coverallsapp/github-action@v2.2.0
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info